### ISSUE TITLE
"Newer version available below" showing up on latest version

### ISSUE THREAD

**Issue by LazyBoot** [archon810/apkmirror-public#32]
#### Expected behavior
I would expect the latest version of an app to not have the text "There's a newer version available below!"

#### Actual behavior
![capture](https://user-images.githubusercontent.com/3827482/30768987-f2574c52-a010-11e7-96a2-8cb354a13623.PNG)
Screenshot taken at: https://www.apkmirror.com/apk/dji-technology-co-ltd/dji-go-4/dji-go-4-4-1-10-release/dji-go-4-for-drones-since-p4-4-1-10-android-apk-download/

**Comment by archon810** [comment]
I think it's happening because some of the releases have 2 variants, and the 2nd variant starts with a 2, whereas the one you linked starts with a 1 and its internal version is technically smaller.

We've had trouble coming up with a full proof algorithm to compare release versions, though in this case it's pretty obvious 4.1.10 is highest. But if you go strictly by internal apk version, there are other higher ones.

**Comment by archon810** [comment]
@SeBsZ Do we have a plan to resolve this?

**Comment by TPS** [comment]
What's interesting is that, in certain views, you _do_ have APKs sorted in strictly descending order, & other views, it seems to go by upload time (as here).

**Comment by archon810** [comment]
This issue is now fixed.
