### ISSUE TITLE
Error 1015, Rate Limited & Banned

### ISSUE THREAD

**Issue by igkillabeeiv** [archon810/apkmirror-public#40]
Within android app downloading apps to update & this error 1015 page pops up with message You are being rate limited & the owner of apkmirror banned me with my 
![screenshot_20171117-202921](https://user-images.githubusercontent.com/33772296/32976918-23c209c0-cbd7-11e7-90a0-2d365bbd7517.png)

**Comment by archon810** [comment]
1. We don't have an Android app, and any unofficial Android app is unsupported.

2. This kind of throttling happens when you exceed a certain number of requests to download or release pages in a certain period of time that is in place to prevent leeching, hammering, etc. The block lifts after a little while.

**Comment by archon810** [comment]
Keep in mind that using download managers that split up files into little bits and download them all at once may exacerbate the issue and prompt the throttling block much sooner.
